### ISSUE TITLE
alias插件替换路径错误

### ISSUE THREAD

**Issue by SSylow** [electron-vite/vite-electron-plugin#18]
如果import的文件存在位置是在同级目录下或者是同级目录文件，就会错误。
如：
`/electron/main/index.ts `
需要引用来自
`/electron/main/win/window.ts`
配置为
```
alias([{
  find: '@M',
  replacement: path.join(__dirname, 'electron/main'),
}]),
```
在index.ts中，我是这样写
`import { test } from "@M/win/windows";`
最终转换后得到path `/test/windows`
实际需要得到的path `./test/windows`
缺少一个点

我debug代码后发现是
/plugin/index.ts文件中第49行：
`replacement = path.posix.relative(path.dirname(importer), replacement)`
这个代码如果是我这种引用同级目录下文件，或者引用同级文件，得到的值都是空字符串。

因为我主业是Java，略懂前端，所以也不知道咋改合适。

**Comment by caoxiemeihao** [comment]
你用的 Windows 可以在你机器上调试下试试，最好提个 PR 修复下，也没几行代码。
我平时用的 Mac，要等到周末才有空找个 Windows 试试。

**Comment by SSylow** [comment]
不是呢，我的也是Mac，系统是12.4的，node 18.10.0的
暂时是这样改的
```
replacement = path.posix.relative(path.dirname(importer), replacement)
replacement += './'
```
主要我是干Java的 我也不知道这样改会不会其他问题，先保证编译通过😂

**Comment by caoxiemeihao** [comment]
哦对了，应该是没判空。看看这段代码实现呢，应该能解决问题了。
https://github.com/vite-plugin/vite-plugin-utils/blob/f1338ce01bb6259797a195fc428db88ce5519dd9/function/index.ts#L56-L68
<img width="397" alt="image" src="https://user-images.githubusercontent.com/26263658/198451807-1c8c7c23-e045-4dde-b5f8-ad461365e41a.png">

**Comment by caoxiemeihao** [comment]
`v0.4.7` 试下
