### ISSUE TITLE
window环境下plugin-alias错误

### ISSUE THREAD

**Issue by keyiis** [electron-vite/vite-electron-plugin#19]
问题已经解决了一部分，路径解析已经正确了，但是还有问题
我的代码目录如下：
![1666925372751](https://user-images.githubusercontent.com/7766085/198482378-d28e72f1-c55b-419e-be22-a9fbc659d662.png)
vite配置：
![1666925580475](https://user-images.githubusercontent.com/7766085/198482275-8c4b0904-59c8-4b92-9b4b-63b85bbc2db6.png)
弄完后我提交个pr

**Comment by keyiis** [comment]
补充下，有没有可能打包成一个文件

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-electron-plugin/issues/18
在这个 issues 中讨论
