### ISSUE TITLE
环境变量获取不到

### ISSUE THREAD

**Issue by keyiis** [electron-vite/vite-electron-plugin#21]
我在项目根目录下配置了环境变量
![1666936165028](https://user-images.githubusercontent.com/7766085/198512745-d93ec06b-a3c9-46ad-aedb-5ca33ae7ee39.png)
![1666936329445](https://user-images.githubusercontent.com/7766085/198513162-932af571-2997-4090-b392-ee984d5eec51.png)

但是在electron目录下的代码里用以下两种方式均无法获取
`import.meta.env.VITE_SERVER_BASE_API`
`process.env.VITE_SERVER_BASE_API`

**Comment by caoxiemeihao** [comment]
使用下 `dot-env` 获取

**Comment by keyiis** [comment]
@caoxiemeihao 我把模板生成的vite.config.js稍微做了下修改，然后从`process.env`中读取vite环境变量
![1666939542152](https://user-images.githubusercontent.com/7766085/198521188-3d2a680d-a0ec-4b54-8e33-3747f272369f.png)

**Comment by caoxiemeihao** [comment]
你这到给我提了个醒，后面会考虑将功能集成到插件中

**Comment by keyiis** [comment]
我这个方法还是有问题，只解决了dev下获取变量的问题，打包后还是获取不到

**Comment by caoxiemeihao** [comment]
所以说，要在转换层实现。

**Comment by keyiis** [comment]
是的，那么目前版本有实现还是实现有问题？或者是否有思路？

**Comment by caoxiemeihao** [comment]
用插件的 transform 转换下代码

**Comment by keyiis** [comment]
好的，我试试

**Comment by keyiis** [comment]
@caoxiemeihao 我平时vite用的不多，有点疑问向您请教：
默认情况下vite在编译代码时是不是应该会自动替换代码里的import.meta.env？我看了vue的vite插件，里面没有看到手工转换的步骤，所以这个转换过程是不是一定得手工实现，是不是能通过配置告诉vite？

**Comment by caoxiemeihao** [comment]
https://github.com/vitejs/vite/blob/47a78db49740daee873525de90d0e44b19883771/packages/vite/src/node/plugins/define.ts#L51-L56

**Comment by keyiis** [comment]
@caoxiemeihao 还是没搞懂:joy:。我的理解不知道对不对，从你给的链接看vite已经在definePlugin里做了环境变量的处理，而且是在esbuild之后，那么你的插件是替代了vite默认的esbuild，但是后面的插件还是应该正常执行。而且我发现你的插件esbuild执行后，import.meta变成了import_meta,而且多了一行`const import_meta = {};`，不知道这是不是环境变量没有替换成功的原因，我尝试通过esbuild.transform的参数define来实现import.meat.env.key替换，是可以做到，但我总感觉这不是一个好办法
![1667037792835](https://user-images.githubusercontent.com/7766085/198825533-d0e70e0e-7131-4744-bb27-772801d78ee0.png)

**Comment by caoxiemeihao** [comment]
你可以看看 `v0.5.0` 的代码，已经实现了 `loadViteEnv()` 插件。
https://github.com/electron-vite/vite-electron-plugin/blob/7666a05aeb08f2700a1be1301f1affd2b606edae/plugin/index.ts#L142
不过这两天不打算发版，我要学些其它的东西。文档还要改改，计划周一发版。

**Comment by keyiis** [comment]
@caoxiemeihao 多谢解答！我觉得还是用`import.meta.env`比较合适，而不是合并到`process.env`，因为`process.env`里的值可以在运行时修改，而`import.meta.env`更适合用于设置固定不变的值。我先用下面的方法解决问题
![1667051675519](https://user-images.githubusercontent.com/7766085/198835410-280c4b8a-74ff-4149-8031-4c5f60a329aa.png)

**Comment by caoxiemeihao** [comment]
你讲的有道理，我也改成了 `import.meta.env`
