### ISSUE TITLE
build后axios无法在主进程中访问

### ISSUE THREAD

**Issue by keyiis** [electron-vite/vite-electron-plugin#23]
在主进程中使用如下方法引入了axios
`import axios, { AxiosResponse } from 'axios';`
dev环境下没有问题，但是build后运行报错
![1666943754049](https://user-images.githubusercontent.com/7766085/198534866-4728a15d-f80a-4a26-afe7-b7dbd43284ae.png)

**Comment by caoxiemeihao** [comment]
放到 `dependenices` 中。
可以进 [Discord](https://github.com/electron-vite/electron-vite-vue/issues/222) 的中文区讨论

**Comment by keyiis** [comment]
@caoxiemeihao 可以了，谢谢！好的
