### ISSUE TITLE
feature request: be able to bundle preload script

### ISSUE THREAD

**Issue by johnheroy** [electron-vite/vite-electron-plugin#31]
For security reasons, `require` is not defined in the special context in which preload scripts run, but it would be useful for preload scripts to be able to share constants (i.e., method names) between preload scripts and IPC implementations for the APIs exposed in preload scripts.

This feature request is to suggest being able to build the preload scripts with esbuild `--bundle` option so there is no need for require at runtime.

**Comment by caoxiemeihao** [comment]
`vite-plugin-electron` will be bundle Preload-scripts

**Comment by caoxiemeihao** [comment]
More about vite-plugin-electron
https://github.com/electron-vite/vite-plugin-electron/issues/107
