### ISSUE TITLE
[help] 设置alias后找不到ts模块

### ISSUE THREAD

**Issue by subframe7536** [electron-vite/vite-electron-plugin#32]
在`alias`样例中，我将`common/foo.js`修改为`common/foo.ts`，运行后报错：`Error: Cannot find module ../common/foo'`

想请教一下如何修改配置？是需要在electron启动前把`common`中的`ts`编译成`js`吗？

foo.ts
```ts
export const foo = '@common/foo.ts'
```

main.ts
```ts
- import foo from '@common/foo'
+ import { foo } from '@common/foo'
```

**Comment by caoxiemeihao** [comment]
把 common 放到 `include` 里面，就会被编译成 .js 文件

**Comment by subframe7536** [comment]
感谢，我之前找到的一直是在tsconfig里配😅
