### ISSUE TITLE
建议npm包的`package.json` 里的 `types` 不要使用 `src` 目录

### ISSUE THREAD

**Issue by mengxinssfd** [electron-vite/vite-electron-plugin#33]
建议 `npm` 包的 `package.json` 里的 `types` 不要使用 `src` 目录。

否则用户使用了更严格的`tsconfig` 时，当  `tsc` 检查到 `import` 了此 `npm` 包的文件，还会检查进此包的 `src` 目录，从而导致 `tsc` 失败；且无法排除出去，使用 `exclude`、`skipLibCheck` 都不起效。

**Comment by caoxiemeihao** [comment]
可以的，下个版本独立 types 声明
