### ISSUE TITLE
Missing package after building

### ISSUE THREAD

**Issue by CharlesBT** [electron-vite/vite-electron-plugin#35]
Hi,

I have added     "electron-devtools-installer": "^3.2.0", to my devDependencies.
At application launch I've got an application error telling electron-devtools-installer is missing.
If I build with  electron-devtools-installer added to dependencies instead of devDependencies, it works.

Is there a way to keep the package in the devDependencies and have it working ?
Do I need to do some plugin config for that ?

I have tried :  include: ['electron', 'node_modules/electron-devtools-installer'], but it fails

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Demo? 👀

**Comment by CharlesBT** [comment]
Sorry this issues non longer exist
