### ISSUE TITLE
打包后图片资源文件路径不正确

### ISSUE THREAD

**Issue by Likunone** [electron-vite/vite-electron-plugin#36]
这是不正确的路径 少个 /assets 路径 js文件是正确的。
<img width="524" alt="image" src="https://user-images.githubusercontent.com/15193414/201559737-4d7c8167-5fea-4f2b-8e56-02a1cc2d9767.png">

这是我vite.config.js的配置参数
<img width="522" alt="image" src="https://user-images.githubusercontent.com/15193414/201559989-3cd61aa6-004c-4073-9011-e50ac63625d9.png">

**Comment by caoxiemeihao** [comment]
```diff
export default {
+ build: {
+   assetsDir: '', // electron-vite-vue#287
+ },
}
```
