### ISSUE TITLE
How to change location of electron main process code?

### ISSUE THREAD

**Issue by hatton** [electron-vite/vite-electron-plugin#44]
I would like to put my `main/index.ts` under `src/`, so that I have `src/main/index.ts`. I tried 

```diff
  plugins: [
    electron({
-      include: ["electron"],
+      include: ["src/main"] 
```
and in `package.json`,

```diff
-  "main": "dist-electron/main/index.js",
+  "main": "dist-electron/index.js",
```

But then `electron-dist` is not even created.

Can you see what I'm doing wrong? Thanks.

**Comment by caoxiemeihao** [comment]
`v0.6.4` is out!
