### ISSUE TITLE
Cannot use global variables replacements in electron

### ISSUE THREAD

**Issue by harishpanneerselvam** [electron-vite/vite-electron-plugin#52]
Not able to set global variables in electron. it is throwing ReferenceError: `__APP_NAME__` is not defined.

![image](https://user-images.githubusercontent.com/33625676/211049340-dcca0384-2a97-4d95-ba8d-a6a0cd28ee12.png)

**Comment by caoxiemeihao** [comment]
vite.config.js

```js
{
  define: {
    __APP_NAME__: '"hello"',
  },
}
```
