### ISSUE TITLE
environment variables not exposed

### ISSUE THREAD

**Issue by treboryx** [electron-vite/vite-electron-plugin#53]
![image](https://user-images.githubusercontent.com/5408097/212553659-7e2d4a38-595e-4478-b356-50a95e44b486.png)

My setup is:

Electron main in: `src/main/main.ts` 

Config is: `include: ["src/main"]`

App loads fine, but the environment variables are not exposed. `env` in `import.meta` is not typed and doesn't work, only `resolve` and `url`

How can I expose environment variables in main.ts and maybe in `src/main.tsx`?

**Comment by caoxiemeihao** [comment]
[plugins: [loadViteEnv()]](https://github.com/electron-vite/vite-electron-plugin/blob/v0.7.3/examples/quick-start/vite.config.ts#L15)

**Comment by treboryx** [comment]
> [plugins: [loadViteEnv()]](https://github.com/electron-vite/vite-electron-plugin/blob/v0.7.3/examples/quick-start/vite.config.ts#L15)

Hey, thanks for the quick reply.

That piece of code is there by default, and in my case it's also there, but doesn't seem to expose environment variable or make import.meta.env typed

**Comment by caoxiemeihao** [comment]
Not a clear requirement, can you provide a simple reproduction Demo?

**Comment by treboryx** [comment]
> Not a clear requirement, can you provide a simple reproduction Demo?

https://github.com/treboryx/electron-vite-reproduction

Check `electron/main/index.ts` line 16 & 17. Run it and it'll log undefined values.

**Comment by treboryx** [comment]
> ```diff
> - console.log("process.env", process.env.TEST_ENV);
> + console.log("import.meta.env", import.meta.env.TEST_ENV);
> ```

Oops, that was a typo but it still doesn't work.

![image](https://user-images.githubusercontent.com/5408097/212694033-e131d077-98e1-4973-9348-e16fc26f56cc.png)


![image](https://user-images.githubusercontent.com/5408097/212694004-88c7dc18-767a-48d6-a802-49631fa9a984.png)

![image](https://user-images.githubusercontent.com/5408097/212694070-5214f922-7aa5-4cec-912d-e1c75a94d41b.png)

**Comment by caoxiemeihao** [comment]
https://vitejs.dev/config/shared-options.html#envprefix
```diff
- TEST_ENV=true
+ VITE_TEST_ENV=true
```
